### NumPy ndarrays

Unlike python list, *NumPy arrays* must contain elements of the same data type(dtype)

1. numpy.ndarray.shape returns the dimensiom of a NumPy array
2. 

__Using a 1-D Array of Integers (Rank #1 Array)__


In [ ]:
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

# We print information about x
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print('x has dimensions:', x.shape)
print('x has size:', x.size)

x =  [1 2 3 4 5]


__Using 1-D Array of Strings (Rank #1 Array)__

In [ ]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


__Using a 1-D Array of Int and String (Rank #1 Array)__

***NumPy will assign each element a same datatype because NumPy arrays must contains elements of same type.***

In [ ]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape) 
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


__Using a 1-D Array of Float, and specifying the datatype of each element as int64__

***NOTE*** - Precision will be lost in this example

In [ ]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

__Using a 2-D Array (Rank #2 Array)__

In [ ]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print information about Y
print('Y = \n', Y)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32
Y has dimensions: (4, 3)
Y has a total of 12 elements


__Save the NumPy array to a File__

In [ ]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

In [ ]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print information about the ndarray we loaded
print('Y = \n', y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

Y = 
 [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


### Using built-in functions to create ndarrays

__Create a Numpy array of zeros with a desired shape `np.zeros((row,column), dtype)`__

In [ ]:
# We create a 3 x 4 ndarray full of zeros. 
#np.zeros((row,column), dtype)

X = np.zeros((3,4), dtype=int)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


__Create a Numpy array of ones__

In [ ]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))

# We print X
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


__Create a Numpy array of constants__

In [ ]:
# We create a 2 x 3 ndarray full of fives. 
X = np.full((2,3), 5) 

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


__Create a Numpy array of Identity matrix__

In [ ]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


__Create a Numpy array with entries in the main diagonal omly__

In [ ]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]



__Create a Numpy array of evenly spaced values in a given range, using `arange(stop_val)`__

See the complete syntax of `NumPy.arange()` [here](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [10]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


__Create a Numpy array using `arange(start_val, stop_val)`__

Note: `np.arange` returns values from start_val to stop_val (exclusive)

In [11]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


__Create a Numpy array using `arange(start_val, stop_val, step_size)`__

Note: `np.arange` returns values from start_val to stop_val (exclusive)

In [ ]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,19,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 1  4  7 10 13 16]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


__Create a Numpy array using `linspace(start, stop, n)`, with `stop` inclusive.__

See the all possible arguments in the syntax [here](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) 

In [12]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)

# We print the ndarray
print()
print('x = \n', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


__Create a Numpy array using `linspace(start, stop, n, endpoint = False)`, with `stop` excluded.__

In [ ]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
x = np.linspace(0,25,10, endpoint = False)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


__Create a Numpy array by feeding the output of `arange()` function to the  `reshape()` function.__    

Here, `arange()` function will give you a 1-D array, whereas the `reshape()` function will convert that 1-D array into a  desired shape. **Note:  the  `size` of the final output must be as same as the `size` of the initial  1-D array.

In [ ]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


__Create a Numpy array by calling the `reshape()` function from the output of `arange()` function.__

Notice the change in the arguments of `reshape()`

In [ ]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


__Create a rank 2 Numpy array by using the `reshape()` function.__

In [ ]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


__Create a Numpy array using the `numpy.random.random()` function.__

In [ ]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.37159182 0.48012243 0.43113424]
 [0.54324015 0.39333419 0.42217558]
 [0.57867261 0.11036061 0.01209802]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


__Create a Numpy array  using the `numpy.random.randint()` function.__

In [ ]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[11 10]
 [10  8]
 [ 6  4]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


__Create a Numpy array of "Normal" distributed random numbers, using the `numpy.random.normal()` function.__

In [ ]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.23149677 -0.09510317 -0.11851652 ... -0.05776124  0.0500089
   0.01633683]
 [ 0.0187887   0.00231631  0.15106805 ...  0.01805368  0.17640193
  -0.1877434 ]
 [ 0.12935997 -0.023331    0.05660583 ... -0.06336443  0.0582949
   0.07443578]
 ...
 [-0.11776789 -0.01671674  0.15160675 ... -0.08099091 -0.01746606
  -0.09083542]
 [-0.07743734  0.21125682 -0.10716137 ...  0.09110855 -0.11867854
   0.05117121]
 [ 0.0293684   0.07118385  0.06729154 ...  0.0021676   0.0056668
   0.02679587]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -1.5480608418062565e-05
The maximum value in X is: 0.4822622163842484
The minimum value in X is: -0.5067436990371555
X has 499797 negative numbers
X has 500203 positive numbers


In [ ]:
np.random.binomial(100,0.5,100).mean()

50.35

<h1> Accessing, Deleting and Inserting Elements into ndarrays</h1>

__Accessing and Modifying Elements of 1-D Array__

In [30]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([6, 7, 8, 9, 10])

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])
print()

##MODIFY

# We change the fourth element in x from 4 to 20
x[3] = 70

# We print x after it was modified 
print('Modified:\n x = ', x)

This is First Element in x: 6
This is Second Element in x: 7
This is Fifth (Last) Element in x: 10

This is First Element in x: 6
This is Second Element in x: 7
This is Fifth (Last) Element in x: 10

Modified:
 x =  [ 6  7  8 70 10]


__Accessing and Modifying Elements of 2-D array__

Note: The first row and column of an 2-D array are accessed using `np.array[0,0]`

In [27]:
X = np.array([1, 2, 3, 4, 5,6,7,8,9]).reshape(3,3)
print()
print('X = \n', X)
print()


## ACCESS
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])
print()

## MODIFYING

X[0,0] = 798

print('Modified X = \n', X)


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9

Modified X = 
 [[798   2   3]
 [  4   5   6]
 [  7   8   9]]


__Deleting Elements of an Array__

To delete elements from a 2-D array, use: `np.delete(ndarray, elements_position, axis = 0 or 1)`

- axis = 0 is used to select rows
- axis = 1 is used to select columns

In [33]:
w = np.array([2,4,6,8,67]) 

print('Original array w = ', w)
print()
## Deleting
w = np.delete(x,[0,4])
print('Edited w = ', w)

Original array w =  [ 2  4  6  8 67]

Edited w =  [ 7  8 70]


In [34]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


__Append Elements to an Array `numpy.append(array, values, axis=None)` or `np.append(ndarray, elements, axis)`__

In [35]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

## append 6,7,8,9 to x and name it v
v = np.append(x,[6,7,8,9])
print(v)


##

[1 2 3 4 5 6 7 8 9]


In [40]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

## Append a new row containing 7,8,9 and store it in a variable U

U = np.append(Y, [[7,8,9]], axis = 0)
print(U)
print()

## Append a new column containing 7,8,9 to Y and store it in a variable UU

UU = np.append(Y, [[7],[8]], axis = 1)
print(UU)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 7]
 [4 5 6 8]]


__Insert Elements in an Array : `np.insert(ndarray, index, elements, axis)`__

This function inserts the given list of elements to ndarray right before the given index along the specified axis

In [41]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]


In [43]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We print w
print()
print('w = \n', w)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,13, axis=1)
print()
print('v = \n', v)


Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[ 1 13  2  3]
 [ 7 13  8  9]]


__Stack Arrays__

`numpy.hstack`: column-wise stacking

`numpy.vstack`: row-wise stacking



In [44]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


__Slicing ndarrays__

1. `ndarray[start:end]` : select elements between the start and end indices
2. `ndarray[start:]`: select all elements from the start index till the last index
3. `ndarray[:end]` : select all elements from the first index till the end index

In [46]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

print('X = \n', X)
print()

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



In [50]:
## Select elements through slicing..

# We select all the elements that are in the 2nd through 5th rows and in the 3rd to 5th columns
Z = X[1:5,2:5]

# We print Z
print('Z = \n', Z)
print()

# We can select the same elements as above using method 2
W = X[1:,2:]
print('W = \n', W)

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


Note: when we perform slices on ndarrays and save them into new variables, the data is not copied into the new variable. 
Rather, X, W and Z are now just three different names for the same ndarray. Therefore, slicing only creates a view of the original array.

Thus, a modifying the element in the new variables created from a slice modifies the original variable.

To avoid this, the `numpy.ndarray.copy()`



In [51]:
Z[3,2] = 1999    ##Changing the last element in Z would change the last element in X without the copy method

print('X = \n', X)

X = 
 [[   0    1    2    3    4]
 [   5    6    7    8    9]
 [  10   11   12   13   14]
 [  15   16   17   18   19]
 [  20   21   22   23 1999]]


__Demonstrating the copy function__

In [55]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)


# We select all the elements that are in the 2nd through 5th rows and in the 3rd to 5th columns
Q = np.copy(X[1:5,2:5])

##OR

WW = X[1:5,2:5].copy()

# We print Z
print('Q = \n', Q)
print()


Q[3,2] = 1999    ##Changing the last element in Q would change the last element in X without the copy method

print('Q = \n', Q)
print()

WW[1,2] = 599    ##Changing the last element in WW

print('WW = \n', WW)
print()

print('X = \n', X)


Q = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]

Q = 
 [[   7    8    9]
 [  12   13   14]
 [  17   18   19]
 [  22   23 1999]]

WW = 
 [[  7   8   9]
 [ 12  13 599]
 [ 17  18  19]
 [ 22  23  24]]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


__The `unique()` function__

The `np.unique(ndarray)` function returns the unique elements in the given ndarray

In [56]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]


__Boolean Indexing__

In [57]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])



Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]


In [58]:
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



__Set Operations__

- `np.intersect1d(x,y))` : checks intersection between two array
- `np.setdiff1d(x,y)` : checks for element in x and not in y
- `np.union1d(x,y)` : All elements of x and y

In [59]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]
